### ISSUE TITLE
While Building new theme i am facing this problem

### ISSUE THREAD

**Issue by tharungithub** [zkoss/zkThemeTemplate#12]
0 info it worked if it ends with ok
1 verbose cli [ 'D:\\DigiGOV\\Themes\\node-v10.16.0-win-x64\\node.exe',
1 verbose cli   'D:\\DigiGOV\\Themes\\node-v10.16.0-win-x64\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '--global',
1 verbose cli   'zklessc@latest' ]
2 info using npm@6.9.0
3 info using node@v10.16.0
4 verbose npm-session 4b1e6041623dee4d
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 404 http://registry.npmjs.org/zklessc 1314ms
8 http fetch GET 404 http://registry.npmjs.org/zklessc 903ms
9 silly fetchPackageMetaData error for zklessc@latest 404 Not Found - GET http://registry.npmjs.org/zklessc - Not found
10 timing stage:rollbackFailedOptional Completed in 1ms
11 timing stage:runTopLevelLifecycles Completed in 3293ms
12 verbose stack Error: 404 Not Found - GET http://registry.npmjs.org/zklessc - Not found
12 verbose stack     at res.buffer.catch.then.body (D:\DigiGOV\Themes\node-v10.16.0-win-x64\node_modules\npm\node_modules\npm-registry-fetch\check-response.js:104:15)
12 verbose stack     at process._tickCallback (internal/process/next_tick.js:68:7)
13 verbose statusCode 404
14 verbose pkgid zklessc@latest
15 verbose cwd D:\NewThemeZk\digigov-themes-padma
16 verbose Windows_NT 10.0.10586
17 verbose argv "D:\\DigiGOV\\Themes\\node-v10.16.0-win-x64\\node.exe" "D:\\DigiGOV\\Themes\\node-v10.16.0-win-x64\\node_modules\\npm\\bin\\npm-cli.js" "install" "--global" "zklessc@latest"
18 verbose node v10.16.0
19 verbose npm  v6.9.0
20 error code E404
21 error 404 Not Found - GET http://registry.npmjs.org/zklessc - Not found
22 error 404
23 error 404 'zklessc@latest' is not in the npm registry.
24 error 404 You should bug the author to publish it (or use the name yourself!)
25 error 404 Note that you can also install from a
26 error 404 tarball, folder, http url, or git url.
27 verbose exit [ 1, true ]

**Comment by scribetw** [comment]
It's `zkless-engine@latest`, not `zklessc`
