### ISSUE TITLE
Build dependency issue 

### ISSUE THREAD

**Issue by dustinkredmond** [zkoss/zkThemeTemplate#13]
I am receiving below. I've cloned the repo and run the following successfully.

`./init.sh`
`npm install`

When I run the `mvn clean package` I'm receiving the following output.

C:\Users\Me\Desktop\zkThemeTemplate-master>mvn clean package
[INFO] Scanning for projects...
[INFO]
[INFO] ----------------------< org.example:exampletheme-theme >-----------------------
[INFO] Building example-theme 1.0.0
[INFO] --------------------------------[ jar ]---------------------------------
[WARNING] The POM for org.zkoss.zk:zkmax:jar:9.0.0.FL.20190912-Eval is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.672 s
[INFO] Finished at: 2019-12-05T15:27:51-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project example-theme: Could not resolve dependencies for project org.example:exampletheme:jar:1.0.0: Failure to find org.zkoss.zk:zkmax:jar:9.0.0.FL.20190912-Eval in http://mavensync.zkoss.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of ZK CE has elapsed or updates are forced -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by scribetw** [comment]
Apologized the outdated FL versions were removed since we have released 9.0.0-RC/RC2.

You can modify `<zk.version>9.0.0.FL.20190912-Eval</zk.version>` in pom.xml to fix this issue.
Using `9.0.0-RC2-Eval` is okay.
