### ISSUE TITLE
cannot start

### ISSUE THREAD

**Issue by Nikola-jpg** [zkoss/zkThemeTemplate#17]
jetty:run

[ERROR] Failed to execute goal on project zkessentials: Could not resolve dependencies for project org.zkoss:zkessentials:war:9.0.0-RC2-Eval: Failed to collect dependencies at org.zkoss.zk:zkmax:jar:9.0.0-RC2-Eval -> org.zkoss.zk:zkex:jar:9.0.0-RC2-Eval -> net.sf.jasperreports:jasperreports:jar:6.6.0 -> com.lowagie:itext:jar:2.1.7.js6: Failed to read artifact descriptor for com.lowagie:itext:jar:2.1.7.js6: Could not transfer artifact com.lowagie:itext:pom:2.1.7.js6 from/to ZK EE (https://maven.zkoss.org/repo/zk/ee): Authentication failed for https://maven.zkoss.org/repo/zk/ee/com/lowagie/itext/2.1.7.js6/itext-2.1.7.js6.pom 401 Unauthorized -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

Failure to find com.lowagie:itext:pom:2.1.7.js6 in http://mavensync.zkoss.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of ZK CE has elapsed or updates are forced

**Comment by hawkchen** [comment]
The `itext` is included automatically by `jasperreport`. You can specify ZK version with `9.6.1-Eval` which doesn' t include `itext` by default.

If you have to use 9.0, you can exclude `jasperreport` manually in your pom.xml.
